### ISSUE TITLE
Corrupt state

### ISSUE THREAD

**Issue by jstaro** [AmmyUI/AmmyUI#37]
I've been working all day, converting an old WPF app to use XAML, which has been going generally great, but when I moved some "global" aliases and mixins from the bottom of my `MainWindowFunctions.ammy` file to the top, everything became messed up. Whatever I seem to do now, all my mixins are marked with squigglies and the error `Redefinition of '<name of mixin>'`.

Things I have tried so far, which haven't helped:
* Commenting out all but one mixin
* Cutting out everything but one mixin of the file
* Cleaning the solution in VS
* Removing the `bin` and `obj` folders outside of VS
* Removing `MainWindow.g.xaml`
* Closing VS, removing those folders, plus the `.vs` folder and restarting VS and reloading the solution
* Unloading and reloading the offending project
* Removing everything from `MainWindowFunctions.ammy`, and every usage from the `MainWindow.ammy ` file let's me compile. I can then add some aliases which seem to work fine, but adding the simplest mixin (without using it in `MainWindow.ammy`) just gives me that "Redefinition" error again (and adding that mixin marks the previously working aliases as erroneous as well).
* Uninstalling Ammy 1.1.25 (which took 3 VS restarts to fully complete) and installing 1.1.29

It seems there is some state laying around somewhere that is corrupt, and I don't know where or how to start over from a clean slate.

Ammy v1.1.29, VS 2015 Community Edition Update 3, Windows 7 x64

**Comment by jstaro** [comment]
Some further testing revealed this strange behaviour:
![clipboard image 14](https://cloud.githubusercontent.com/assets/4079934/22401140/7631ff98-e5c9-11e6-97a8-476c3df8a9d7.png)
![clipboard image 15](https://cloud.githubusercontent.com/assets/4079934/22401141/79dd09d0-e5c9-11e6-950a-279d277b9537.png)
![clipboard image 16](https://cloud.githubusercontent.com/assets/4079934/22401144/7f88b60e-e5c9-11e6-9162-a28d17088bbc.png)

**Comment by jstaro** [comment]
![clipboard image 17](https://cloud.githubusercontent.com/assets/4079934/22401162/533ca3d4-e5ca-11e6-8724-4e4a8f09ed62.png)
Putting these on the same line makes it work.

**Comment by ionoy** [comment]
Hm, I copied you example symbol for symbol and it still works for me:

![image](https://cloud.githubusercontent.com/assets/592624/22402497/eaa845a2-e601-11e6-8c1a-10df65eba6ce.png)

Can you post full source to gist or somewhere?

Also, are you using XamlToAmmy to convert your XAML files? I would like to know about issues with it. I know it doesn't do much now. It should at the very least convert "x:Name" and "x:Key" attributes automatically. But is there anything else?

**Comment by jstaro** [comment]
I'm having trouble creating a minimum reproducible example. Only this project is messed up. I can paste this mixin file to a clean project and it is fine. That is why I thought some cache or something was corrupted, but the earlier revision worked for some reason, and the diff gives to clue. I'll try to find some time to cut out all non-essential distracting stuff from this project.

Meanwhile, I found out that as long as the beginning of the file starts with either "alias" or "mixin" (I actually had a commented-out namespace import and then an empty line in the above examples, sorry about that), the mixins work again, so at least I can still work. That means I can't import any namespaces in the file, but that's okay for now. I did inspect the file in a hex editor and it looks normal. There's just a BOM at the start of the file.

I decided to convert the project by hand, line by line, to try to find out what works best as mixins and aliases, etc. It's not a lot of XAML, so it's been going fine.

**Comment by ionoy** [comment]
Thanks for trying to investigate the issue, but you don't really have to do that :) Just, if next time you see that  this bug, save file and copy it somewhere. Then you can send it to to info@ammyui.com or post it here. Anyway, thanks again!

**Comment by Kngrektor** [comment]
I think I've managed a [minimal repro](https://gist.github.com/Kngrektor/0b41ed026be335aa475523c1ff56f85e). I was playing around with using AmmyUI and Elmish.WPF, everything worked great until I added a mixin to the file.
I also tried moving it to another file and removing the BOM, nothing helped.
